### ISSUE TITLE
cvaegan diverge when dataset is cifar10

### ISSUE THREAD

**Issue by xzqjack** [tatsy/keras-generative#1]
Hi, your "keras-generative" implementation is really fascinating.
When training the  cvaegan.py on cifar10 with your code and hyper-setting parameters, the generator diverge and the generated image are noise -like. I haven't try celebA dataset. 
Have you generated real-like image with cvaegan.py? Is there any setting i should have pay attention to? 
I look forward your reply. Thanks in advance.

**Comment by xtarx** [comment]
Same here when trained  using ali.py ,but the other-way around the discriminator diverge

**Comment by tatsy** [comment]
Talking about the dataset cifar10, I think it is a little difficult to generate real-like image because the variation of the data is quite wide.
So, maybe neither the algorithm CVAE-GAN nor ALI will not generate real-like images, while I have not tested them.
