### ISSUE TITLE
reconstruct exact input

### ISSUE THREAD

**Issue by tsly123** [tatsy/keras-generative#13]
Hi,
Thank you for your work. 
Currently, I am working with the CVAEGAN and reconstruct face with emotion, and I want to exactly reconstruct the input as normal autoencoder does and keep the discriminator as the same time.  My thought is to change the discriminator **binary_crossentropy** ([here](https://github.com/tatsy/keras-generative/blob/master/models/cvaegan.py#L55)) loss by **mse**?
Is it right?

Thank you.
tsly

**Comment by tatsy** [comment]
Sorry, but your question is not due to the issue of my code. Let me close this issue.
