### ISSUE TITLE
g_acc  close to 0 and  d_acc close to 1

### ISSUE THREAD

**Issue by HubertStone** [tatsy/keras-generative#14]
Hello,
Thanks for your work, it's fascinating. But I have a problem when training CVAE-GAN. 
When does the model converge？g_acc  close to 1 and  d_acc close to 0?
And in mnist, I found that g_acc always reduces to 0 very fast, and it seems that the discriminator dominants the generator. So how to solve this problem?
Thanks!

**Comment by tatsy** [comment]
Hi @HubertStone,

I think it's the problem of many classical GANs. Typically, the discriminator learns faster than the generator in the standard GAN. In recent (but rather old today) GANs such as LSGAN and WGAN-GP partly solve the problem. 

Cheers!
