### ISSUE TITLE
GPU requirements

### ISSUE THREAD

**Issue by InderpreetSinghChhabra01** [tatsy/keras-generative#6]
What are the version of Cuda and cudnn required for this code to run.
I am able to run it on cudnn 6 and cuda 7 but not on cudnn 8 and cuda 9.

**Comment by tatsy** [comment]
It depends on which version of Keras and backend API is used.

To my knowledge, my program only depends on Keras and also Tensorflow, and the CUDA and CUDNN versions do not matter.
