### ISSUE TITLE
How can I generate new image through the hdf5

### ISSUE THREAD

**Issue by NiFangBaAGe** [tatsy/keras-generative#8]
@tatsy 
Hi, I have trained cvaegan ,and now I want to generate new image. How can I generate new image through the hdf5.

**Comment by tatsy** [comment]
Hi @NiFangBaAGe,

I'm afraid that I do not prepare a script for generating new images. So, you should write a new script by your own.

This process includes the construction of the network, loading the parameters (from HDF5 file), and then generate a new image. It will help you to see the process to save images in the file ``base.py``

https://github.com/tatsy/keras-generative/blob/master/models/base.py#L137
