### ISSUE TITLE
How can I generate new image through the hdf5?

### ISSUE THREAD

**Issue by NiFangBaAGe** [tatsy/keras-generative#9]
@tatsy 
Hi! How can use the weights in dec_trainer.hdf5 ?
I add a function in cvaegan.py :
    def make_my_image(self,samples):
        self.f_dec.load_weights('/home/liuweihuang/keras-generative/output/cvaegan/weights/epoch_00100/dec_trainer.hdf5')
        self.save_my_images(samples, '/home/liuweihuang/keras-generative/myImg.png')

And it occurs :
ValueError: You are trying to load a weight file containing 4 layers into a model with 11 layers.

**Comment by tatsy** [comment]
Hi @NiFangBaAGe,
I noticed that a problem like you mentioned occurs when you partially load weight HDF5 files. So, please load all the weight files to CVAE-GAN model (even though it is a bit redundant), and then generate a new image.

**Comment by NiFangBaAGe** [comment]
Do you mean    
 def make_my_image(self,samples):
        print ('------make_my_image------')
        self.f_dec.load_weights(
            '/home/liuweihuang/keras-generative/output/cvaegan/weights/epoch_00100/dec_trainer.hdf5')
        self.f_enc.load_weights(
            '/home/liuweihuang/keras-generative/output/cvaegan/weights/epoch_00100/enc_trainer.hdf5')
        self.f_dis.load_weights(
            '/home/liuweihuang/keras-generative/output/cvaegan/weights/epoch_00100/dis_trainer.hdf5')
        self.f_cls.load_weights(
            '/home/liuweihuang/keras-generative/output/cvaegan/weights/epoch_00100/cls_trainer.hdf5')

        self.save_my_images(samples, '/home/liuweihuang/keras-generative/myImg.png')

It still occurs :
ValueError: You are trying to load a weight file containing 4 layers into a model with 11 layers.
